[build]
  command = "npm install --legacy-peer-deps --no-offline && npm run build"
  publish = ".next"
  functions = "netlify/functions"
  edge_handlers = "netlify/edge-handlers"

[build.environment]
  # Versiones de Node.js y npm
  NODE_VERSION = "18.18.0"
  NPM_VERSION = "10.2.4"
  YARN_VERSION = "3.6.4"
  
  # Configuración de npm
  NPM_FLAGS = "--legacy-peer-deps --no-offline --no-audit --progress=true"
  NPM_TOKEN = "${NPM_TOKEN}"
  NODE_VERBOSE = "true"
  NPM_CONFIG_PREFER_OFFLINE = "false"
  NPM_CONFIG_AUDIT = "false"
  NPM_CONFIG_PROGRESS = "true"
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_UPDATE_NOTIFIER = "false"
  NPM_CONFIG_LOCKFILE_VERSION = "2"
  
  # Configuración de Next.js
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_OPTIONS = "--max-old-space-size=4096"
  NEXT_SHARP_PATH = "/opt/buildhome/.npm/lib/node_modules/sharp"
  NODE_USE_SHARP = "1"
  
  # Variables de entorno de Firebase (configuradas en la UI de Netlify)
  NEXT_PUBLIC_FIREBASE_API_KEY = "${FIREBASE_API_KEY}"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "${FIREBASE_AUTH_DOMAIN}"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "${FIREBASE_PROJECT_ID}"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "${FIREBASE_STORAGE_BUCKET}"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "${FIREBASE_MESSAGING_SENDER_ID}"
  NEXT_PUBLIC_FIREBASE_APP_ID = "${FIREBASE_APP_ID}"
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID = "${FIREBASE_MEASUREMENT_ID}"

# Plugin de Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirecciones
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Encabezados de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com https://apis.google.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://www.google-analytics.com https://region1.google-analytics.com https://*.googleapis.com https://*.firebaseio.com https://*.firebase.com https://identitytoolkit.googleapis.com; frame-src 'self' https://www.google.com https://www.youtube.com https://www.google.com/recaptcha/ https://recaptcha.google.com/recaptcha/ https://www.google.com/maps/; frame-ancestors 'none'; form-action 'self' https://identitytoolkit.googleapis.com; base-uri 'self'; object-src 'none';"

# Encabezados de caché para activos estáticos
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
