[build]
  command = "npm ci && npm run build"
  publish = ".next"
  functions = ".netlify/functions"

[build.environment]
  # Versiones de Node.js y npm
  NODE_VERSION = "18.18.0"
  NPM_VERSION = "10.2.4"
  
  # Instalar dependencias de desarrollo
  NPM_FLAGS = "--production=false --legacy-peer-deps"
  
  # Configuración de Next.js
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_OPTIONS = "--max_old_space_size=4096"
  
  # Variables de entorno de Firebase (ajustar según sea necesario)
  NEXT_PUBLIC_FIREBASE_API_KEY = "${FIREBASE_API_KEY}"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "${FIREBASE_AUTH_DOMAIN}"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "${FIREBASE_PROJECT_ID}"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "${FIREBASE_STORAGE_BUCKET}"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "${FIREBASE_MESSAGING_SENDER_ID}"
  NEXT_PUBLIC_FIREBASE_APP_ID = "${FIREBASE_APP_ID}"
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID = "${FIREBASE_MEASUREMENT_ID}"

# Configuración para producción
[context.production]
  command = "npm run build"
  publish = ".next"
  
  [context.production.environment]
    NODE_ENV = "production"
    NEXT_PUBLIC_BASE_URL = "https://tudominio.com"

# Configuración para previsualizaciones de despliegue
[context.deploy-preview]
  command = "npm run build"
  publish = ".next"
  
  [context.deploy-preview.environment]
    NODE_ENV = "production"
    NEXT_PUBLIC_BASE_URL = "${DEPLOY_PRIME_URL}"

# Configuración para despliegues de rama
[context.branch-deploy]
  command = "npm run build"
  publish = ".next"
  
  [context.branch-deploy.environment]
    NODE_ENV = "production"
    NEXT_PUBLIC_BASE_URL = "${DEPLOY_PRIME_URL}"

# Configuración del plugin de Next.js para Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"
  
  [plugins.inputs]
    # Habilitar funciones de servidor de Next.js
    functions_src = ".next"
    functions_dist = ".netlify/functions"

# Redirecciones para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Configuración de cabeceras de seguridad
[headers]
  # Aplicar a todas las rutas
  for = "/*"
  
  [headers.values]
    # Seguridad básica
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    
    # Política de seguridad de contenido (CSP)
    # Ajustar según las necesidades de tu aplicación
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com https://apis.google.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      img-src 'self' data: https:;
      font-src 'self' https://fonts.gstatic.com;
      connect-src 'self' https://www.google-analytics.com https://region1.google-analytics.com https://*.googleapis.com https://*.firebaseio.com https://*.firebase.com https://identitytoolkit.googleapis.com;
      frame-src 'self' https://www.google.com https://www.youtube.com https://www.google.com/recaptcha/ https://recaptcha.google.com/recaptcha/ https://www.google.com/maps/;
      frame-ancestors 'none';
      form-action 'self' https://identitytoolkit.googleapis.com;
      base-uri 'self';
      object-src 'none';
    """

# Configuración para desarrollo local
[dev]
  command = "npm run dev"
  port = 3000
  publish = ".next"
  targetPort = 3000
  
  [dev.environment]
    NODE_ENV = "development"
    NEXT_PUBLIC_BASE_URL = "http://localhost:3000"

# Configuración de caché para mejorar el rendimiento
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, must-revalidate"

# Configuración específica para archivos estáticos
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.gif"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configuración para archivos de mapa de fuente
[[headers]]
  for = "/*.map"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
